#!/bin/bash

# Script constants
PROJECT_DIR="/home/jovyan"
PROJECT_WORK_DIR="$PROJECT_DIR/work"
PROJECT_RESOURCE_DIR="$PROJECT_DIR/res"

# Header
echo "Set up script for Spark container."

# Create the resource directory if it doesn't exist
if [ ! -d "$PROJECT_RESOURCE_DIR" ]; then
    echo "Creating resource directory..."
    mkdir "$PROJECT_RESOURCE_DIR"
fi

# Check whether the tutorials have been set up
if [ ! -d "$PROJECT_WORK_DIR/tutorials" ]; then
    echo "Tutorials haven't been set up."
    
    # Download the tutorials file
    echo "Downloading tutorial resources..."
    wget -O "$PROJECT_RESOURCE_DIR/tutorials.v0.3.zip" "https://dl.dropboxusercontent.com/u/8495623/hhs-p7-spark-docker/tutorials_v0.3.zip"

    # Set up the assignments
    echo "Setting up tutorials..."
    cd "$PROJECT_WORK_DIR"
    unzip ../res/tutorials.v0.3.zip
    cd -

    # Remove the tutorials resources
    rm "$PROJECT_RESOURCE_DIR/tutorials.v0.3.zip"
fi
echo "Tutorials have been set up."

# Check whether the assignments have been set up
if [ ! -d "$PROJECT_WORK_DIR/assignments" ]; then
    echo "Assignments haven't been set up."
    
    # Download the assignments file
    echo "Downloading assignment resources..."
    wget -O "$PROJECT_RESOURCE_DIR/assignments.v0.2.zip" "https://dl.dropboxusercontent.com/u/8495623/hhs-p7-spark-docker/assignments_v0.2.zip"

    # Set up the assignments
    echo "Setting up assignments..."
    cd "$PROJECT_WORK_DIR"
    unzip ../res/assignments.v0.2.zip
    cd -

    # Remove the assignments resources
    rm "$PROJECT_RESOURCE_DIR/assignments.v0.2.zip"
fi
echo "Assignments have been set up."

# Check whether the tutorials data has been set up
if [ ! -f "$PROJECT_WORK_DIR/tutorials/data/babynames.csv" ]; then
    echo "Tutorials data hasn't been set up."
    
    echo "Copying data from assignments to tutorials..."
    cp "$PROJECT_WORK_DIR/assignments/data" "$PROJECT_WORK_DIR/tutorials/" -R
fi
echo "Tutorials have been set up."

echo "Spark container set up is done."

