#!/bin/bash

# Get the current path
MY_PATH="`dirname \"$0\"`"

# Script constants
PROJECT_WORK_DIR="$MY_PATH/work"
PROJECT_RESOURCE_DIR="$MY_PATH/res"

# Header
echo "Installation script."

# Pull the docker image
echo "Updating container image..."
sudo docker-compose -f "$MY_PATH/docker-compose.yml" pull

# Create the work directory
if [ ! -d "$PROJECT_WORK_DIR" ]; then
    echo "Createing working directory..."
    mkdir "$PROJECT_WORK_DIR"
    sudo chmod 777 "$PROJECT_WORK_DIR"
fi

echo "Installation is done."

