#!/bin/bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Get the current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Script constants
NOTEBOOK_DIR="$DIR/notebook"

# Header
echo "Starting installation..."

# Pull the docker image
echo "Pulling container image..."
sudo docker-compose -f "$DIR/docker-compose.yml" pull

# Create the notebook directory
if [ ! -d "$NOTEBOOK_DIR" ]; then
    echo "Creating notebook directory..."
    mkdir "$NOTEBOOK_DIR"

    echo "Setting proper directory permissions..."
    sudo chmod 777 "$NOTEBOOK_DIR"
fi

echo "Installation finished!"

