#!/bin/bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Get the current path
MY_PATH="`dirname \"$0\"`"

# Script constants
PROJECT_NOTEBOOK_DIR="$MY_PATH/notebook"

# Header
echo "Installation script."

# Pull the docker image
echo "Pulling container image..."
sudo docker-compose -f "$MY_PATH/docker-compose.yml" pull

# Create the work directory
if [ ! -d "$PROJECT_NOTEBOOK_DIR" ]; then
    echo "Creating notebook directory..."
    mkdir "$PROJECT_NOTEBOOK_DIR"
    sudo chmod 777 "$PROJECT_NOTEBOOK_DIR"
fi

echo "Installation is done."

