#!/bin/bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Get the current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Script constants
PROJECT_NAME="spark"

# Include global functions
. "$DIR/src/functions"

# Stop the docker container and detach
log_info "Stopping running Spark containers in Docker..."
sudo docker-compose -p "$PROJECT_NAME" stop
log_info "Use './start' to restart the container."
log_success "All Spark containers have been stopped."
echo

