#!/bin/bash

# Script constants
PROJECT_NAME="spark"

# Start the docker container and detach
echo "Stopping running Spark container in Docker..."
sudo docker-compose -p "$PROJECT_NAME" stop
echo "All Spark containers have been stopped."

