#!/bin/bash

# Get the current path
cd "`dirname \"$0\"`"

# Header
echo "Container update script."

echo "Fetching new updates..."
git fetch

echo "Checking out latest version..."
git checkout origin master

cd -
echo "Done."

