#!/bin/bash

# A script to easly force an update before starting the container, if there's
# any update available.
#
# This is an alias for running the following commands:
# * ./update
# * ./start

# Elevate permissions
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Run the update and start script
./update
./start
