#!/bin/bash

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Get the current path
cd "`dirname \"$0\"`"

# Header
echo "Updating container scripts..."

# Stop running containers
./stop

echo "Fetching new updates..."
git fetch

echo "Checking out latest version..."
git checkout origin/master

cd -
echo "Update done."

