#!/bin/bash

export PYSPARK_PYTHON=/opt/conda/pkgs/python3
export PYSPARK_DRIVER_PYTHON=jupyter
export PYSPARK_DRIVER_PYTHON_OPTS="
    notebook
    --NotebookApp.open_browser=False
    --NotebookApp.ip='*'
    --NotebookApp.port=8888
    --port=8888
    --no-browser
    --notebook-dir=/root/notebook"

pyspark --conf spark.driver.maxResultSize=3g --driver-memory 3g
