#!/bin/bash

# Script to push the built image to Docker Hub.
# Pushing makes the container automatically available for all other users that 
# are using this container.
#
# Environment variables:
# $DOCKER_USER: Username of the Docker Hub account the image should be pushed
#               to. The image won't be pushed if left blank.
# $DOCKER_PASS: Password of the Docker Hub account the image should be pushed
#               to. The image won't be pushed if left blank.

# Elevate permissions
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Script constants
DOCKER_IMAGE="timvisee/hhs-p7-spark-docker"

# Include global functions
. "$DIR/../src/functions"

# Make sure any image exists that can be pushed
if [[ "$(docker images -q $DOCKER_IMAGE 2> /dev/null)" == "" ]]; then
    log_warning "There's no image build available that can be pushed."
    log_info "Use the './build' or './build-and-push' script to build the image."
    exit
fi

# Log in with docker
if [ -n "$DOCKER_USER" ] && [ -n "$DOCKER_PASS" ]; then
    log_info "Automatically logging into Docker..."
    sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
else
    log_info "Requesting docker login..."
    sudo docker login
fi

# Push the image
log_info "Pushing the image..."
sudo docker push "$DOCKER_IMAGE"

# Show a success message
log_success "Image successfully pushed!"

