#!/bin/bash

# Elevate permissions
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

# Script constants
DOCKER_IMAGE="timvisee/hhs-p7-spark-docker"

# Make sure any image exists that can be pushed
if [[ "$(docker images -q $DOCKER_IMAGE 2> /dev/null)" == "" ]]; then
    echo "There's no image build available that can be pushed."
    echo "Use the './build' or './build-and-push' script to build the image."
    exit
fi

# Log in with docker
if [ -n "$DOCKER_USER" ] && [ -n "$DOCKER_PASS" ]; then
    echo "Automatically logging into Docker..."
    sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
else
    echo "Requesting docker login..."
    sudo docker login
fi

# Push the image
echo "Pushing the image..."
sudo docker push "$DOCKER_IMAGE"

# Show a success message
echo "Image successfully pushed!"

